from pathlib import Path
import json,hashlib,subprocess
root=Path('/private/tmp/careops-c14-closeout-20261005');child=root/'libs/kairos';out=root/'conductor/evidence/c1.4-completion-20261005'
old_task_ids={t['id'] for t in json.loads((root/'conductor/execution/tasks.json').read_text())['tasks']}
g=subprocess.check_output(['git','rev-parse','HEAD'],cwd=child,text=True).strip()
ci=json.loads((out/'child-final-pr-checks.json').read_text());assert ci['headRefOid']==g
checks=ci['statusCheckRollup'];assert len(checks)==50 and all(x['status']=='COMPLETED' and x['conclusion'] in ['SUCCESS','SKIPPED'] for x in checks)
skips=[x['name'] for x in checks if x['conclusion']=='SKIPPED'];assert set(skips)=={'Q5.2 canonical native regression (Ubuntu)','Codecov OIDC upload'}
owner=json.loads((out/'child-final-native-owner.json').read_text());assert owner['headSha']==g and owner['conclusion']=='success'
assert all(x['exit_code']==0 and x['head']==g for x in json.loads((out/'governance-final-receipts.json').read_text()))
review=json.loads((out/'final-integrated-review.json').read_text());assert review['disposition']=='accept' and review['integrated_commit']==g
p=root/'conductor/evidence/d2.4-kairos-contract.json';d=json.loads(p.read_text());previous=d['kairos_commit'];existing=set(d['source_sha256']);assert len(existing)==132;d['kairos_commit']=g;d['owner_ci'].update(head_sha=g,conclusion='success',run_url=owner['url'])
paths=set(d['source_sha256']);paths.update(json.loads((out/'final-source-preservation.json').read_text())['c1_runtime_sha256'])
paths.update(subprocess.check_output(['git','diff','--name-only',previous,g],cwd=child,text=True).splitlines());d['source_sha256']={n:hashlib.sha256((child/n).read_bytes()).hexdigest() for n in sorted(paths) if (child/n).is_file()};assert existing<=set(d['source_sha256'])
d['c14_reviewed_qualification']={'acceptance':'conductor/evidence/c1.4-completion-20261005/acceptance.json','previous_accepted_q52_commit':previous,'runtime_source':'7f72b7d9a9b6ae62e481a59b2cc04ce37da0a4a5','independent_review':'conductor/evidence/c1.4-completion-20261005/final-integrated-review.json','development_only':True,'broader_current_child_checks_all_green':True,'expected_conditional_skips':skips};p.write_text(json.dumps(d,indent=2)+'\n')
p=root/'conductor/current-state.json';d=json.loads(p.read_text());d['submodule_pins']['libs/kairos']=g;d['next_action']=d['next_action'].replace('broader child CI/security/release, calibration phase C1.4,','security/release,').replace('Development pin retains accepted C-01 and C1 independent readback.',f'Development pin {g} completes reviewed C1.4 synthetic ingestion qualification, preserves accepted Q5.2, and passes broader child CI.');d['context_paths'].append('conductor/evidence/c1.4-completion-20261005/README.md');p.write_text(json.dumps(d,indent=2)+'\n')
p=root/'conductor/tracks/empirical_calibration_20260925/plan.md';s=p.read_text().replace('- [ ] C1.4 Conductor','- [x] C1.4 Conductor').replace('C1.4 phase review remains open.','C1.4 phase review passes at the reviewed integrated development pin; see [C1.4 closeout](../../evidence/c1.4-completion-20261005/README.md).').replace('666 files verified, counts conserved, and C1.4 remains open.','Historical readback retained. Fresh corrected independent readback verifies 666 files and conserves counts; [C1.4 closeout](../../evidence/c1.4-completion-20261005/README.md) records final integrated CI and governance acceptance.');s=s.replace('source PR #211 remains unmerged while broader gates fail.','source PR #211 historical source remains unmerged; broader gates pass on the C1.4 successor pin.').replace('source PR #212 remains unmerged while broader gates fail.','source PR #212 historical source remains unmerged; broader gates pass on the C1.4 successor pin.');p.write_text(s)
note=f'''\n## C1.4 accepted synthetic ingestion phase — 2026-10-05\n\nReviewed integrated development pin `{g}` preserves accepted Q5.2 and the\n90 exact tested C1 source files. Fresh native tests and C-01 runs, 666 independent\nIPC/Parquet file reads, schema/units/nulls, negative controls and input/accepted/\nexcluded/censored count reconciliation pass. Final source has 48 successful\nhosted checks and two documented conditional skips; phase, DAG, strict-clean and\nevidence-boundary checks pass. See [C1.4 completion](../../evidence/c1.4-completion-20261005/README.md).\nHistorical failed attempts remain retained. C2, public API review, clinical\nvalidation and release remain open. Earlier proposed/planning statements describe\ntheir original delivery, superseded for C0/C1 only by recorded acceptance.\n'''
for name in ['handoff.md','test-matrix.md']:
 p=root/'conductor/tracks/empirical_calibration_20260925'/name;p.write_text(p.read_text()+note)
p=root/'conductor/module-readiness.md';p.write_text(p.read_text()+note.replace('../../evidence/','evidence/'))
p=out/'acceptance.json';d=json.loads(p.read_text());d.update(status='accepted_synthetic_C1_phase',C1_complete=True,final_head_ci={'successful':48,'expected_conditional_skips':skips,'native_owner_url':owner['url']},final_integrated_review='final-integrated-review.json');p.write_text(json.dumps(d,indent=2)+'\n')
(out/'README.md').write_text(f'''# C1.4 accepted synthetic ingestion phase — 2026-10-05\n\nC1.4 is accepted at reviewed Kairos development pin `{g}` ([PR 217](https://github.com/edithatogo/kairos/pull/217)). C1.1–C1.4 are complete within the declared synthetic ingestion scope.\n\nRuntime source `7f72b7d9a9b6ae62e481a59b2cc04ce37da0a4a5` has fresh native lint/format/test proof, C-01 physical and actual transport runs, typed Arrow IO and C0 mapping/accounting checks. `final-source-preservation.json` proves the 90 C1 runtime files unchanged at the integrated pin and retains 32 accepted Q5.2 paths. Replicas and byte aliases are labeled separately from actual transport executions and distinct records.\n\nIndependent corrected readback passes 666 files, types, units, logical null/empty/absent observations, eleven negative checks and count reconciliation. Exact verifier/report/receipt hashes and bounded independent acceptance are in `child-independent-review.json`. The retained child archive contains 1,969 fully hashed members (5,509,128 bytes), SHA-256 `1955ee5a36dc190cf83e7af308c0231a3aed92a4f0e17b0604b108b6ca013a03`, at `libs/kairos/conductor/evidence/c1.4-integrated-20261005/qualification.tar.gz`. Rejected readback and failed setup attempts remain preserved.\n\nFinal-head hosted CI records 48 successful checks and two expected conditional skips: {', '.join(skips)}. The native owner aggregate and both native hosts pass. Feature-minimal and Rust 1.88 IO, Rust 1.76 workspace/default Arrow and other compatibility jobs pass. `child-final-pr-checks.json` and `child-final-native-owner.json` bind actual final head. `governance-final-receipts.json` records phase/DAG/strict-clean/boundary checks at that head. The prior inline registry-comment phase failure is retained in `governance-attempt-2734588-*`; standalone comments preserve the existing parser and statuses.\n\n`previous-pin-contract.json` and `previous-current-state.json` preserve Q5.2's accepted baseline and historical runtime/canonical results. The pin contract retains every previous source key and adds reviewed C1 proof. Q5.3/Q5.4, C2, public API review, clinical validation and release remain open. Child development qualification is separate from merging the historical upstream PR stack or release acceptance.\n''')
subprocess.run(['python3','tools/tasks.py','build'],cwd=root,check=True)
import sys
sys.path.insert(0,str(root/'tools'));import tasks
catalog=tasks.derive(root);assert {t['id'] for t in catalog['tasks']}==old_task_ids;by={t['id']:t for t in catalog['tasks']};p=root/'conductor/execution/mvp/recipes.json';recipes=json.loads(p.read_text())
for row in recipes['tasks']:
 parent=by[row['task_id']];row['task_objective_sha256']=hashlib.sha256(parent['objective'].encode()).hexdigest();row['parent_dependencies']=parent['dependencies'];row['context_sources']=parent['context_paths'];row['source']=parent['source']
p.write_text(json.dumps(recipes,indent=2)+'\n')
print('Prepared reviewed C1 completion records and preserved previous pin contract keys:',len(existing),'->',len(paths))
